# Generated by Django 6.0.4 on 2026-05-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentData',
            fields=[
                ('consent_data_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'consent_data',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
